// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTRswXfDYPvMSIQ6RImLCrK3Bl_3eNio8',
    appId: '1:392258731303:web:e1132d62596d43987d3d02',
    messagingSenderId: '392258731303',
    projectId: 'bonus-tracker-app-da46f',
    authDomain: 'bonus-tracker-app-da46f.firebaseapp.com',
    storageBucket: 'bonus-tracker-app-da46f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsDo9UX7U87sPa6-iG95GN5egsaBedvuw',
    appId: '1:392258731303:android:d578c79a522723277d3d02',
    messagingSenderId: '392258731303',
    projectId: 'bonus-tracker-app-da46f',
    storageBucket: 'bonus-tracker-app-da46f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwOR-HRQh4Weq8Vhb5vVIDa7GXbMjOCJM',
    appId: '1:392258731303:ios:b4ce1e3c0426e8527d3d02',
    messagingSenderId: '392258731303',
    projectId: 'bonus-tracker-app-da46f',
    storageBucket: 'bonus-tracker-app-da46f.firebasestorage.app',
    iosBundleId: 'com.example.bonusTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwOR-HRQh4Weq8Vhb5vVIDa7GXbMjOCJM',
    appId: '1:392258731303:ios:b4ce1e3c0426e8527d3d02',
    messagingSenderId: '392258731303',
    projectId: 'bonus-tracker-app-da46f',
    storageBucket: 'bonus-tracker-app-da46f.firebasestorage.app',
    iosBundleId: 'com.example.bonusTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTRswXfDYPvMSIQ6RImLCrK3Bl_3eNio8',
    appId: '1:392258731303:web:42b7ad87212a137d7d3d02',
    messagingSenderId: '392258731303',
    projectId: 'bonus-tracker-app-da46f',
    authDomain: 'bonus-tracker-app-da46f.firebaseapp.com',
    storageBucket: 'bonus-tracker-app-da46f.firebasestorage.app',
  );
}
